"""add error mitigation

Revision ID: 26f038113f80
Revises: bb46de4107af
Create Date: 2024-10-30 13:46:46.635996

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "26f038113f80"
down_revision = "bb46de4107af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Job", schema=None) as batch_op:
        batch_op.add_column(sa.Column("error_mitigation", sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Job", schema=None) as batch_op:
        batch_op.drop_column("error_mitigation")

    # ### end Alembic commands ###
