"""Add transient job state

Revision ID: 3a3f8c2e7096
Revises: a3d1af905d3e
Create Date: 2024-07-05 14:38:35.442843

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a3f8c2e7096"
down_revision = "a3d1af905d3e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "TransientJobState",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.INTEGER(), nullable=False),
        sa.Column("program_id", sa.INTEGER(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["Job.id"], name=op.f("fk_TransientJobState_job_id_Job"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["QuantumProgram.id"],
            name=op.f("fk_TransientJobState_program_id_QuantumProgram"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_TransientJobState")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("TransientJobState")
    # ### end Alembic commands ###
