"""qprov

Revision ID: 7fe9c959db45
Revises: 3a3f8c2e7096
Create Date: 2024-09-09 13:53:03.776668

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7fe9c959db45"
down_revision = "3a3f8c2e7096"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Device", schema=None) as batch_op:
        batch_op.add_column(sa.Column("qprov_id", sa.UUID(), nullable=True))

    with op.batch_alter_table("Provider", schema=None) as batch_op:
        batch_op.add_column(sa.Column("qprov_id", sa.UUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Provider", schema=None) as batch_op:
        batch_op.drop_column("qprov_id")

    with op.batch_alter_table("Device", schema=None) as batch_op:
        batch_op.drop_column("qprov_id")

    # ### end Alembic commands ###
