"""error_mitigation

Revision ID: 9aac847198b4
Revises: 7fe9c959db45
Create Date: 2024-11-04 16:52:31.363008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aac847198b4'
down_revision = '7fe9c959db45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_mitigation', sa.String(length=50), nullable=False))

    with op.batch_alter_table('TransientJobState', schema=None) as batch_op:
        batch_op.add_column(sa.Column('circuit_fragment_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TransientJobState', schema=None) as batch_op:
        batch_op.drop_column('circuit_fragment_id')

    with op.batch_alter_table('Job', schema=None) as batch_op:
        batch_op.drop_column('error_mitigation')

    # ### end Alembic commands ###
