"""persistent transpilation cache

Revision ID: bb46de4107af
Revises: 3a3f8c2e7096
Create Date: 2024-09-11 15:17:20.530642

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bb46de4107af"
down_revision = "3a3f8c2e7096"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "TranslatedProgram",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("quantum_circuit", sa.BLOB(), nullable=False),
        sa.Column("is_string", sa.BOOLEAN(), nullable=False),
        sa.Column("assembler_language", sa.String(length=50), nullable=False),
        sa.Column("translation_distance", sa.INTEGER(), nullable=False),
        sa.Column("program_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["QuantumProgram.id"],
            name=op.f("fk_TranslatedProgram_program_id_QuantumProgram"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_TranslatedProgram")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("TranslatedProgram")
    # ### end Alembic commands ###
