apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: broker
  name: broker
  namespace: default
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: broker
status:
